### ISSUE TITLE
Quick start

### ISSUE THREAD

**Issue by Rock-kestrel** [Paulymorphous/Road-Segmentation#8]
Hello!

I'm a newbie here, could you please  help me with getting started?

I'm trying now testing your pretrained model, but don't understand how yet.
First, what files do I need? Road_mapper_final.h5? Anything else?

Really sorry for that, but could you please show step-by-step, how could one use it from the beginning? If it's not too complicated...

Thanks a lot!:)

**Comment by Paulymorphous** [comment]
Hi @Rock-kestrel,
Don't apologise for starting out at something, we all have been there.

1. Clone this Repo
2. You can use Src/MapPredictions.ipynb to run this model on your own map images.
3. Since this model is trained on 256x256 images, you will have to split your image into smaller 256x26 image. I have written a function which does just that in Src/MapPredictions.ipynb. Also, I will write a prediction script for this in a week. Maybe you can use that. 

You can read and learn more about this project [here](https://towardsdatascience.com/road-segmentation-727fb41c51af?source=friends_link&sk=47cbffb333ef8518bff7c8e65dee0ae8).

Cheers

**Comment by Rock-kestrel** [comment]
@Paulymorphous, thank you for reply!

Trying now to follow your instructions, there are strings in MapPredictions as follows:
build_model = load_model("../Models/buildings.h5", custom_objects={'soft_dice_loss': soft_dice_loss, 'iou_coef': iou_coef, 'dice_coef_loss':dice_coef})

And it says: "no such file or directory". What is it for and how do I get it? Cause I see only road_mapper_2.h5 and road_mapper_final.h5 in the directory Models

P.S. 
Yeah, besides, there's also a string:
    blank_image = np.zeros((1500 img, 1500, 3), dtype = float)

And it doesn't work... I thought this "img" after the 1st argument is a misprint and removed it. Was I right?
